project:
  type: website


website:

  title: "Seismic-Wave-HPC"
    
#  announcement: 
#    icon: exclamation-triangle
#    dismissable: true
#    content: "**Alert** - This web site is under construction. The structure of the web might be significantly changed. Please be patient. Thank you!" 
#    type: primary
#    position: below-navbar

  body-header: "---"

  draft-mode: visible
   
  navbar:
    left:
      - text: Home
        href: index.md

      - text: "スパコン利用法"
        href: HPC/hpc-howto.md

      - text: "地震波伝播数値シミュレーション講習会"
        href: FDM-Workshop/fdm-workshop.md
 
      - text: "OpenSWPC関連情報"
        href: OpenSWPC-Howto/OpenSWPC-00-index.md

         
    
  sidebar: 

    - title: "スパコン利用法"
      contents: 
        - HPC/hpc-howto.md
        - auto: "HPC/共通知識"
        - auto: "HPC/EIC-2025"
        - auto: "HPC/Wisteria"
        - auto: "HPC/Miyabi"
#        - HPC/Archives/Archives.md
#        - auto: "HPC/Archives/EIC2020"

          
    - title: "地震波数値シミュレーション講習会"
      contents: 
        - FDM-Workshop/fdm-workshop.md
        - auto: "FDM-Workshop/2025年度講習会"

    - title: "OpenSWPC-Howto"
      contents: 
        - OpenSWPC-Howto/OpenSWPC-00-index.md
        - title: 
          href: OpenSWPC-Howto/OpenSWPC-01-build.md
          contents:
          - auto: "OpenSWPC-Howto/OpenSWPC-01-build/*"
 

  google-analytics: "G-MZJMGT1XB0"

format:
  html:
    theme: default
    css: styles.css
    toc: true
    highlight-style: tango
    code-overflow: wrap

#author: Takuto Maeda
bibliography: reference.bib
#suppress-bibliography: true
csl: american-geophysical-union.csl
